views/file_views.py
from blog import *
from flask import Blueprint, request, send_file
from werkzeug.utils import secure_filename
import os

bp = Blueprint("files", __name__, url_prefix='/files')

# 메인 HTML 렌더링
@bp.route('/main/')
def main_page():
    return render_template('index.html')


# 업로드 HTML 렌더링
@bp.route('/upload/')
def upload_page():
    return render_template('upload.html')


# 파일 업로드 처리
@bp.route('/uploadcheck/', methods =['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        file = request.files['file'] # POST 방식으로 업로드페이지에서 넘어오면 file이라는 이름의 폼으로 전송된 파일을 가져옴
        file.save('./uploads/'+secure_filename(file.filename)) # 파일이름을 보호하고 file.save로 파일 객체를 지정한 폴더에 저장한다
        file_list = os.listdir("./uploads")
        return render_template('check.html', file_list=file_list)


# 다운로드 HTML 렌더링
@bp.route('/download/')
def down_page():
    file_list = os.listdir("./uploads")
    return render_template('download.html', file_list=file_list)


# 파일 다운로드 처리
@bp.route('/fileDownload/', methods = ['GET','POST'])
def down_file():
    if request.method == 'POST':
        sw = 0
        file_list = os.listdir("./uploads")
        for x in file_list:
            if(x==request.form['file']):
                sw = 1
        path = "./uploads/"
        return send_file(path + request.form['file'],
                         attachment_filename=request.form['file'],
                         as_attachment=True)


# 파일 리스트 HTML 렌더링
@bp.route('/list/')
def list_page():
    file_list = os.listdir("./uploads")
    # html = """ <center><a href="/">홈페이지</a><br><br>"""
    # html += "file_list: {}".format(file_list) + "</center>"
    # return html
    return render_template('list.html', file_list=file_list)

views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect
from blog import *

bp = Blueprint('main', __name__, url_prefix='/')


# 메인페이지 HTML 렌더링
@bp.route('/')
def home_page():
    return render_template('login.html')

templates/check.html
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
  <head>
    <title>check</title>
  </head>

  <body>
    <center><h1>Upload Page</h1></center>
    <center><a href="{{url_for('files.main_page')}}">홈페이지</a><br><br><br>
    <center>
    <img src="{{ url_for('static',filename='images/check.png') }}", width="100"
      style="margin-left: auto; margin-right: auto; display: block;")/>

    <center>
    <p>파일 업로드 성공!<p>
    </form></center>
  </body>
</html>

templates/download.html
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
  <head>
    <title>download</title>
  </head>

  <body>
    <center><h1>Download Page</h1></center>
    <center><a href="{{url_for('files.main_page')}}">홈페이지</a><br></center>
    <hr width="100%" color="black"/>
    <center><h3>Download File!</h3></center>
    <hr width="100%" color="black"/>

    <img src="{{ url_for('static',filename='images/down.png') }}", width="70"
        style="margin-left: auto; margin-right: auto; display: block;")/><br><br>

    <center>
    <form action = "{{url_for('files.down_file')}}" method = "POST"
         enctype = "multipart/form-data">
    <input type = "text" name = "file" />
    <input type = "submit" placeholder="확장자명까지 입력" value="다운로드"/>
    </form></center><br><br><br>

    <hr width="100%" color="black"/>
    <center><h3>File List</h3></center>
    <hr width="100%" color="black"/>

    <img src="{{ url_for('static',filename='images/list.png') }}", width="50"
    style="margin-left: auto; margin-right: auto; display: block;")/><br>

    <ul>
         {% for n in file_list %}
         <center> {{n}} <br> </center>
         {% endfor %}
    </ul>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
  <head>
    <title>ftp_page</title>
  </head>

  <body>
    <center><h1>FTP Server</h1></center>
    <hr width="100%" color="black"/>

    <center>
    <form>
    <img src="{{ url_for('static',filename='images/file.png') }}", width="50"
        style="margin-left: auto; margin-right: auto; display: block;")/>
    <a href="{{url_for('files.upload_page')}}">파일 업로드</a><br><br><br>

    <img src="{{ url_for('static',filename='images/down.png') }}", width="50"
        style="margin-left: auto; margin-right: auto; display: block;")/>
    <a href="{{url_for('files.down_page')}}">파일 다운로드</a><br><br><br>


    <img src="{{ url_for('static',filename='images/list.png') }}", width="50"
        style="margin-left: auto; margin-right: auto; display: block;")/>
    <a href="{{url_for('files.list_page')}}">파일 목록</a><br><br><br>
    </form>
    </center>
  </body>
</html>

templates/list.html
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
  <head>
    <title>fileList</title>
  </head>

  <body>
    <center><h1>List Page</h1></center>
    <center><a href="{{url_for('files.main_page')}}">홈페이지</a><br></center>
    <hr width="100%" color="black"/>
    <center><h3>Show List!</h3></center>
    <hr width="100%" color="black"/>

    <img src="{{ url_for('static',filename='images/list.png') }}", width="70"
        style="margin-left: auto; margin-right: auto; display: block;")/><br><br>

    <ul>
         {% for n in file_list %}
           <center> {{n}} <br> </center>
         {% endfor %}
    </ul>
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
  <head>
		<title>Login Service</title>
  </head>
  <body><center><div>
  	<h1>Login Page</h1>
  	<hr width="100%" color="black"/>
  	<center>
  		<img src="{{ url_for('static',filename='images/naver.png')}}"/>
  		<h3>Please LOGIN !</h3>
  	</center>
  	<hr width="100%" color="black"/>
  	<a href="{{url_for('files.main_page')}}">홈페이지</a>
	</div></center>
    <hr>
    {% block content %}{% endblock %}
  </body>
</html>

templates/upload.html
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
  <head>
    <title>upload</title>
  </head>

  <body>
    <center><h1>Upload Page</h1></center>
    <center><a href="{{url_for('files.main_page')}}">홈페이지</a><br></center>
    <hr width="100%" color="black"/>
    <center><h3>Upload File!</h3></center>
    <hr width="100%" color="black"/>

    <img src="{{ url_for('static',filename='images/file.png') }}", width="100"
        style="margin-left: auto; margin-right: auto; display: block;")/>

    <br><br><center>
    <form action = "{{ url_for('files.upload_file') }}" method = "POST"
         enctype = "multipart/form-data">
    <input type = "file" name = "file" />
    <input type = "submit"/>
    </form></center>
  </body>
</html>

<!-- http://localhost:5000/uploadcheck -->